# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(566, 726)
        self.imgL = QtWidgets.QLabel(Form)
        self.imgL.setGeometry(QtCore.QRect(30, 120, 500, 420))
        self.imgL.setText("")
        self.imgL.setObjectName("imgL")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(190, 60, 301, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(30, 600, 111, 51))
        self.pushButton.setObjectName("pushButton")
        self.selectBut = QtWidgets.QPushButton(Form)
        self.selectBut.setGeometry(QtCore.QRect(30, 650, 111, 51))
        self.selectBut.setObjectName("selectBut")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(150, 610, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.predText = QtWidgets.QLabel(Form)
        self.predText.setGeometry(QtCore.QRect(150, 660, 401, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.predText.setFont(font)
        self.predText.setObjectName("predText")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "图像预测"))
        self.pushButton.setText(_translate("Form", "选择不同模型"))
        self.selectBut.setText(_translate("Form", "选择图像"))
        self.label_3.setText(_translate("Form", "默认使用的模型：resnet34"))
        self.predText.setText(_translate("Form", "预测结果"))
